# Generated by Django 4.0 on 2022-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='payments',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phonenumber',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
