# Generated by Django 4.0 on 2022-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_location_payments_location_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=50)),
                ('gymname', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
