# Generated by Django 4.0 on 2022-01-07 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_rename_packagename_packages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=50)),
                ('gymname', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
