# Generated by Django 4.0 on 2022-01-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0005_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Booking',
        ),
    ]
