# Generated by Django 4.0 on 2022-01-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locator', '0007_rename_packages_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
