# Generated by Django 4.0 on 2022-01-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0010_alter_booking_gymname_alter_booking_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='gymname',
            field=models.CharField(max_length=250),
        ),
    ]
