# Generated by Django 4.0 on 2022-01-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0012_alter_package_gymname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='gymname',
            field=models.CharField(max_length=250),
        ),
    ]
