# Generated by Django 4.0 on 2022-01-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0013_alter_package_gymname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
