# Generated by Django 4.0 on 2022-01-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0014_remove_booking_package_delete_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gymname', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
